version: "3.9"
    
services:
  ssrb:
    build: ./lambda/ssr/
    volumes:
      - ./lambda/ssr:/app
    ports:
      - "3000:3000"
    environment:
      ORIGIN_BASE_URL: "http://web:80"
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./web/dist:/usr/share/nginx/html
