version: "3.9"
    
services:
  renderer:
    build: ./renderer/
    volumes:
      - ./renderer:/app
    ports:
      - "3000:80"
    environment:
      ORIGIN_BASE_URL: "http://web:80"
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./web/dist:/usr/share/nginx/html
